interop-accessibility repo rename
web-platform-tests/wpt.fyi pull request #3604
Opened 2023-11-13 21:49 UTC by zcorpan

See https://github.com/web-platform-tests/interop-accessibility/issues/72

2023-11-13 23:24 UTC, cookiecrook approved these changes

2023-11-21 15:03 UTC, jcscottiii requested changes
You will need to make the change in interop-data.js as well:

https://github.com/web-platform-tests/wpt.fyi/blob/c5ed4dc1eafeed145002c935dd20593c9060533b/webapp/components/interop-data.js#L317

2023-12-21 18:00 UTC, foolip commented
Ping @zcorpan about the additional change required.

2024-02-06 14:36 UTC, zcorpan commented
Done.

2024-02-27 14:54 UTC, jcscottiii approved these changes

2024-02-27 14:54 UTC, merged